---
:concurrency: 1
:schedule:
  external_posts_collector_worker:
    every: 9m
    class: ExternalPostsCollectorWorker
  external_posts_speaker_worker:
    every: 3m
    class: ExternalPostsSpeakerWorker
  external_posts_scheduled_analyser_worker:
    every: 15m
    class: ExternalPostsScheduledAnalyserWorker
  ad_posts_scheduler_worker:
    cron: '0 8 * * *'
    class: AdPostsSchedulerWorker
